### ISSUE TITLE
remove amd64 from build (Jenkinsfile)

### ISSUE THREAD

**Issue by balcy** [ubports/gcc-5#3]
can we adapt the Jenkinsfile in branch xenial_-_webengine-5-13 so that amd64 is not built ?

https://raw.githubusercontent.com/balcy/gcc-5/xenial_-_jenkinsadaption/Jenkinsfile

both armhf and arm64 do work now with the patch (https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fgcc-5/detail/PR-2/3/pipeline/25) with a non-parallel build.
PR: https://github.com/ubports/gcc-5/pull/2

[Edit: I'm not sure if for building the armhf version of QtWebengine on the server only the arm64 targets of GCC are needed, or the armhf ones as well]

**Comment by UniversalSuperBox** [comment]
No, if we're going to do this, we need it to be around for all architectures.

**Comment by balcy** [comment]
Isn't it possible to just build the armhf QtWebEngine with the patched compiler? I'd then set the additional repository (patched gcc version) for the QtWebEngine build and the respective dependency in the control file of QtWebEngine for this arch (armhf) only. The other architectures can be built using the unmodified gcc.

**Comment by balcy** [comment]
@universalsuperbox could I get write access to the repo? I won't change existing branches but create one for tests.

**Comment by UniversalSuperBox** [comment]
Right... in fact, we could simply rename this package and *only* use it for building QWE on armhf. That way it wouldn't be able to contaminate other package builds... I see you turned off tests, and that will not fly for anything other than a single case that we try to get rid of as soon as possible.

**Comment by balcy** [comment]
yes never change a running system :)

**Comment by balcy** [comment]
yes test are off because of 'not enough ptys' error:
https://github.com/ubports/gcc-5/pull/1#issuecomment-553040297
